app/anahit/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from upload.views import image_upload
from anahit.views import Homepage, AboutUs, ContactUs, ThankYou, ChangeTheme, LinkExpiredView

urlpatterns = [
    #path("", image_upload, name="upload"),
    path('', Homepage.as_view(), name='home'),
    path('about_us', AboutUs.as_view(), name='about_us'),
    path('contact_us', ContactUs.as_view(), name='contact_us'),
    path('users/', include('users.urls')),
    path('sub/', include('subscription.urls'), name="subscription"),
    path('blog/', include('blog.urls'), name="blog"),
    path('services/', include('services.urls'), name="services"),
    path('price/', include('price.urls'), name="price"),
    path('accounts/', include('allauth.urls'), name="accounts"),
    path("admin/", admin.site.urls, name="admin"),
    path('summernote/', include('django_summernote.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("thankyou", ThankYou.as_view(), name="thankyou"),
    path("change_theme", ChangeTheme.as_view(), name="change_theme"),
    path('notification/', include('notifications.urls'), name="notification"),
    path('user/', include('magiclink.urls'), name='magiclink'),
    path('link-expired/',   LinkExpiredView.as_view(), name='link-expired'),

        
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/subscription/urls.py
from django.urls import path

from . import views



urlpatterns = (

    # urls for Subscription
    # path('', views.SubscriptionDetails.as_view(), name='subscription_home'),
    # path('config/', views.stripe_config, name='stripe_config'),
    # path('customer_stripe_details/', views.customer_stripe_details, name='customer_stripe_details'),
    path('create-checkout-session/', views.create_checkout_session, name='checkout_session'),
    # path('create-customer/', views.create_customer, name='create_customer'),
    # path('upgrade_subscription/', views.upgrade_subscription, name='upgrade_subscription'),
    # path('billings/', views.BillingView.as_view(), name='billings'),
    path('plan/', views.plans, name='plans'), 
    path('checkout/<int:product_id>', views.stripe_checkout, name='stripe_checkout'),
    path('create-subscription/', views.createSubscription, name='create-subscription'), 
    path('update-subscription/<str:sub_id>/<str:price_id>/', views.update_subscription, name='update-subscription'),   
    path('success/', views.SuccessView.as_view(), name='stripe_success'),
    path('cancelled/', views.CancelledView.as_view(),name='strip_cancelled'), 
    path('subscription_poll/<sub_id>/', views.subscription_poll, name='subscription_poll'),
    path('webhook/', views.stripe_webhook,name='stripe_webhook'),
    path('cancel-subscription/<str:sub_id>/<str:price_id>/', views.cancel_subscription,name='cancel-subscription'),
    path('update-subscription-status/', views.update_subscription_status,name='update-subscription-status'),


    
)

app/apps/subscription/models.py
from django.db import models
from users.models import User
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField


class Features(models.Model):
    name =  models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.name)

class Service(models.Model):
    name =  models.CharField(max_length=250)
    slug = models.SlugField(max_length = 250, null = True, blank = True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('stripe_checkout', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Service, self).save(*args, **kwargs)

PLAN_TYPE=( 
    ("monthly", "monthly"), 
    ("yearly", "yearly"), 
)
class Plan(models.Model):
    plan_name =  models.CharField(max_length=50,null =True,blank =True)
    price = models.PositiveSmallIntegerField(default=0)
    features = models.ManyToManyField(Features, related_name="plan_features", null=True)
    stripe_price_id = models.CharField(max_length=100,unique=True)
    is_active = models.BooleanField(default=True)
    is_popular = models.BooleanField(default=False)
    plan_type=models.CharField(max_length=40,choices=PLAN_TYPE,default="monthly")
    # rules = models.JSONField()
    # metadata = models.JSONField(null=True, blank=True)

    def __str__(self):
        if self.plan_name==None:
            return "Plan NAME IS NULL"
        return self.plan_name


'''class Coupon(models.Model):
    coupon_code = models.CharField(max_length = 40)
    max_redemptions = models.PositiveIntegerField()
    valid_till = models.DateField()
    discount_percentage = models.FloatField(default=0.0)
    is_active = models.BooleanField(default = False)

    def is_valid(self):
        current_date = timezone.localtime(timezone.now()).date()
        if self.valid_till <= self.current_date:
            return True
        else:
             return False

    def __str__(self):
        return self.coupon_code'''

class Subscription(models.Model):
    user  = models.ForeignKey(User,related_name="user_subscription", 
            null=True, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan,related_name="plan_subs", 
            null=True, on_delete=models.CASCADE)

    stripe_sub =  models.CharField(max_length=100)        
    status  = models.CharField(max_length=30)
    created_at = models.DateTimeField(blank=True,null=True)
    period_start = models.DateTimeField(blank=True,null=True)
    period_end = models.DateTimeField(blank=True,null=True)
    logs = models.JSONField(null=True, blank=True)
    uses = models.JSONField(null=True, blank=True)
    notification_channels = ArrayField(models.CharField(max_length=20), null=True, blank=True)


    def __str__(self):
        if self.stripe_sub==None or self.stripe_sub=="":
            return self.user.email
        return '{}'.format(self.stripe_sub)

app/apps/subscription/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView, TemplateView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse ,HttpResponse, HttpResponseRedirect
import json
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt 
import stripe
import datetime
from . models import Plan, Subscription
from datetime import datetime 
from django.views import View
from .utils import retrieve_subscription_info as get_info


stripe.api_key = settings.STRIPE_SECRET_KEY

# stripe.ApplePayDomain.create(
#   domain_name='example.com',
# )


def create_checkout_session(request):
    if request.method == 'GET':
        
        try:
            # Create new Checkout Session for the order
            # Other optional params include:
            # [billing_address_collection] - to display billing address details on the page
            # [customer] - if you have an existing Stripe Customer ID
            # [payment_intent_data] - lets capture the payment later
            # [customer_email] - lets you prefill the email input in the form
            # For full details see https:#stripe.com/docs/api/checkout/sessions/create

            # ?session_id={CHECKOUT_SESSION_ID} means the redirect will have the session ID set as a query param
            checkout_session = stripe.checkout.Session.create(
                client_reference_id=request.user.id if request.user.is_authenticated else None,
                success_url=request.build_absolute_uri(reverse('stripe_success') )+ '?session_id={CHECKOUT_SESSION_ID}',
                cancel_url=request.build_absolute_uri(reverse('strip_cancelled')),
                payment_method_types=['card'],
                mode = 'subscription',
                line_items=[
                    {
                        'price': 'price_1KdZXhCy95Kg2yHQW0roAm0y',
                        'quantity': 1,
                    }
                ]
            )
            return HttpResponseRedirect(checkout_session.url)
            # return JsonResponse({'sessionId': checkout_session['id']})
        except Exception as e:
            return JsonResponse({'error': str(e)})    


class SuccessView(TemplateView):
    template_name = 'subscription/success.html'


class CancelledView(TemplateView):
    template_name = 'subscription/cancelled.html'

def plans(request):
    plans = Plan.objects.exclude(is_active=False)
    existing_subscription = None
    try:
        existing_subscription = Subscription.objects.get(user=request.user , status="active")
    except :
        pass    

    return render(request, 'subscription/plans.html', {'plans': plans, 'existing_subscription':existing_subscription })    


def stripe_checkout(request ,product_id):
    try:
        try:
            subscription = Subscription.objects.get(user = request.user)
            response = get_info(subscription.stripe_sub)
            user_status = response['data']['status'] # active
            if user_status == 'active':
                return redirect('/price')
        except:
            selected_plan = Plan.objects.get(id=product_id,is_active=True)
            # STRIPE_PUBLISHABLE_KEY
            publishable_key = settings.STRIPE_PUBLISHABLE_KEY
            # existing_pending_subs = None
            # existing_pending_subs = Subscription.objects.get(user=request.user, status = "incomplete")
            
            setup_intent = stripe.SetupIntent.create(
                payment_method_types=["card"],
                usage= "off_session",
            )
            context = {
                        'selected_plan': selected_plan,
                        'setup_intent_secret':setup_intent.client_secret, 
                        'publishable_key':publishable_key
                    }
            return render(request, 'subscription/checkout.html', context)
    except (Plan.DoesNotExist, Subscription.DoesNotExist) as e:
        return HttpResponse(str(e))
    except Exception as error:
        return HttpResponse(str(error))


class PaymentView(View):
    def post(self, request, *args, **kwargs):
        card_num = request.POST['card_num']
        exp_month = request.POST['exp_month']
        exp_year = request.POST['exp_year']
        cvc = request.POST['cvc']

        token = stripe.Token.create(
          card={
            "number": card_num,
            "exp_month": int(exp_month),
            "exp_year": int(exp_year),
            "cvc": cvc
          },
        )

        charge = stripe.Charge.create(
          amount=2000,
          currency="inr",
          source=token, 
          description="Charge for jenny.rosen@example.com"
        )

        if charge['captured'] == True:
            Sale.objects.create(product=product, amount=amount)
            return redirect('app:success_page')

        return redirect('app:fail_page')

@login_required
@csrf_exempt
def createSubscription(request):
    if request.method == 'POST':
        # Reads application/json and returns a response
        data = json.loads(request.body)
        payment_method = data['payment_method']

        try:
          # This creates a new Customer and attaches the PaymentMethod in one API call.
          customer = stripe.Customer.create(
              payment_method=payment_method,
              email=request.user.email,
              invoice_settings={
                  'default_payment_method': payment_method
              }
          )
          stripe.Customer.modify(
                customer.id,
                invoice_settings={
                    'default_payment_method': payment_method
              }
          )

          '''store_card = stripe.Customer.create_source(
            customer.id,
            source="tok_visa",
          )'''

          user = request.user
          user.stripe_id = customer.id
          # user.stripe_card_id = store_card.id
          user.save()

          subscription = stripe.Subscription.create(
              customer=customer.id,
              items=[
                  {
                      "price": data["price_id"],
                  },
              ],
              expand=["latest_invoice.payment_intent"]
          )

          local_sub = Subscription()
          local_sub.user = request.user
          try:
            local_sub.plan = Plan.objects.get(stripe_price_id=data["price_id"])
          except Plan.DoesNotExist:
              pass
          local_sub.stripe_sub = subscription.id
          local_sub.status = subscription.status
          local_sub.created_at = subscription
          local_sub.period_start = datetime.fromtimestamp(subscription.current_period_start)
          local_sub.period_end = datetime.fromtimestamp(subscription.current_period_end)
          
          local_sub.created_at = datetime.fromtimestamp(subscription.start_date)
          if subscription.status == "incomplete" :
                local_sub.logs = {"payment_secret": subscription.latest_invoice.payment_intent.client_secret,
                                  "payment_method": payment_method}
          local_sub.save()

          return JsonResponse(subscription)
        except Exception as e:
          return JsonResponse({'error': (e.args[0]), "data":data }, status=403)
    else:
      return HttpResponse('Get request not allowed')

@csrf_exempt
def subscription_poll(request, sub_id):
    try:
        sub_ob = Subscription.objects.get(stripe_sub =sub_id )
        return JsonResponse({"status": sub_ob.status})
    except Exception as e:
        JsonResponse({'error': str(e)}, status=403)

@csrf_exempt
def update_subscription(request, sub_id ,price_id):
    try:
        subscription_obj = Subscription.objects.get(stripe_sub=sub_id)
        subscription = stripe.Subscription.retrieve(sub_id)
        
        updatedSubscription = stripe.Subscription.modify(
            sub_id,
            # cancel_at_period_end=False,
            payment_behavior="pending_if_incomplete",
            proration_behavior='always_invoice',
            
            items=[{
                'id': subscription['items']['data'][0].id,
                'price': price_id,
               
            }]
        )
        if updatedSubscription.status == 'active':
            subscription_obj.plan = Plan.objects.get(stripe_price_id=price_id)
            subscription_obj.save()
        # return JsonResponse({"updatedSubscription": updatedSubscription})
        if request.GET.get('page') == "price":
            return redirect('price')
        return redirect('my_account')

    except Exception as e:
        return JsonResponse({'error': (e.args[0])}, status=403)

@csrf_exempt
def cancel_subscription(request, sub_id ,price_id):
    try:
        subscription_obj = Subscription.objects.get(stripe_sub=sub_id)
        subscription = stripe.Subscription.retrieve(sub_id)
        
        updatedSubscription = stripe.Subscription.modify(
            sub_id,
            cancel_at_period_end=True,
        )
        if updatedSubscription.status == 'active':
            subscription_obj.plan = Plan.objects.get(stripe_price_id=price_id)
            subscription_obj.save()
        # return JsonResponse({"updatedSubscription": updatedSubscription})
        if request.GET.get('page') == "price":
            
            return redirect('price')
        return redirect('my_account')

    except Exception as e:
        return JsonResponse({'error': (e.args[0])}, status=403)


def update_subscription_status(request):
    try:
        sub_id = request.GET.get('sub_id')
        subscription_status = request.GET.get('subscription_status')
        try:
            user = Subscription.objects.get(user=request.user)

            if subscription_status == 'active':
                updatedSubscription = stripe.Subscription.modify(
                sub_id,

app/templates/subscription/cancelled.html
{% extends "base.html" %}
{% load static %}

{% block style %}

<style>
  .ps-6{
     padding-left: 8rem !important; 
  }
</style>

{% endblock %}


{% block content %}

<div class="main-wrap">
  {% include 'includes/sidebar.html' %}
    
    <div class="right-bar">
      <!-- ======= Header ======= -->
      {% include 'includes/header.html' %}
      <!-- End Header -->
    
      <div>
      </div>
    
      <!-- ======= Footer ======= -->
      {% include 'includes/footer.html' %}
      <!-- End Footer -->
    
      </div>
    </div>
    </div>

{% endblock %}

app/templates/subscription/insign.html
{% extends "base.html" %}
{% load static %}

{% block style %}

<style>
  .ps-6 {
    padding-left: 8rem !important;
  }
</style>

{% endblock %}


{% block content %}


<div class="main-wrap">
  {% include 'includes/sidebar.html' %}

  <div class="right-bar">
    <!-- ======= Header ======= -->
    {% include 'includes/header.html' %}
    <!-- End Header -->

    <div>
      <section class="our_service_section top_section">
        <div class="container">

          <div class="pricing-headings mb-5">
            <h5 class="sub_head text-grey mb-4"><img src="{% static 'img/images/title-Line.png' %}"
                class="head_line">our services</h5>
            <h2 class="primary_head mb-3">Finsights<span class="dot-bg">.</span></h2>
            <p class="p-left ps-0 ms-0 text-grey">Research stocks and understand market trends all in one place</p>
          </div>
          <!-- end heading section -->

          <!-- start our service tabs -->
          <div class="our-service-tabs mb-5">
            <div class="d-md-flex justify-content-between mb-5">
              <div class="search_bar">
                <input autocomplete="off" type="text" name="" id="search-input" class="search_input"
                  placeholder="Search Finsights...">
                <button class="search_btn"><img src="{% static '/img/images/search_icon.png' %}"></button>
              </div>
              <ul class="nav nav-pills mb-3 align-items-center justify-content-end mt-md-0 mt-5" id="pills-tab"
                role="tablist">
                <li class="nav-item me-5" role="presentation">
                  <button class="nav-link active switch_tab" id="pills-profile-tab" data-bs-toggle="pill"
                    data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile"
                    aria-selected="false">
                    <img src="{% static 'img/images/cards_icon.png' %}" class="not-active">
                    <img src="{% static 'img/images/active_cards.png' %}" class="active_img">
                  </button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link switch_tab" id="pills-home-tab" data-bs-toggle="pill"
                    data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home"
                    aria-selected="true">
                    <img src="{% static 'img/images/list_icon.png' %}" class="not-active">
                    <img src="{% static 'img/images/active_list.png' %}" class="active_img">
                  </button>
                </li>
              </ul>
            </div>
            <div class="tab-content" id="pills-tabContent">
              <div class="tab-pane fade" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">

                <div class="ins about_pattern mobile_hide">
                  <div class="c1"></div>
                  <div class="c2"></div>
                  <div class="c3"></div>
                  <div class="c4"></div>
                  <div class="c5"></div>
                  <div class="c6"></div>
                  <div class="c7"></div>
                </div>
                <div class="service-table">
                  <table class="table ">
                    <thead>
                      <tr class="thead_row">
                        <th class="table_head" scope="col">Name</th>
                        <th class="table_head" scope="col">Tags</th>
                        <!-- <th class="table_head" scope="col">Category</th> -->
                      </tr>
                    </thead>
                    <tbody class="service-table-body" id="service-content-table-section">
                      {% for service in service_list %}
                      <tr>
                        <td>
                          <a
                            href="{% if user.is_authenticated %}{% if service.plans.price|slugify == Free_Plan_PRICE %}{{service.link}}{% elif service.plans in user_current_plan %}{{service.link}}{% else %}#{% endif %}{% else %}{% url 'account_login' %}{% endif %}">
                            {{service.title}}</a>
                        </td>
                        <td>{% for tag in service.tags.all %}{{tag.name}} {% endfor %}</td>
                        <td></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <button class="primary_btn subscribe_btn desk-hide border-0">View More</button>
                </div>
              </div>

              <div class="tab-pane show active fade" id="pills-profile" role="tabpanel"
                aria-labelledby="pills-profile-tab">

                <div class="ins about_pattern post_sec_pattrn mobile_hide">
                  <div class="c1"></div>
                  <div class="c2"></div>
                  <div class="c3"></div>
                  <div class="c4"></div>
                  <div class="c5"></div>
                  <div class="c6"></div>
                  <div class="c7"></div>
                </div>
                
                <div class="row" id="service-content-grid-section">
                  {% if services %}
                  {% for service in services %}
                  <div class="col-md-6 col-lg-6 col-sm-12">
                    <a
                    href="{% if user.is_authenticated %}{% if service.plans.price|slugify == Free_Plan_PRICE %}{{service.link}}{% elif service.plans in user_current_plan %}{{service.link}}{% else %}#{% endif %}{% else %}{% url 'account_login' %}{% endif %}">
                    <div class="service-cards post-right mt-5">
                      {% if user.is_authenticated %}{% if service.plans.price|slugify == Free_Plan_PRICE %}{% elif service.plans in user_current_plan %}{% else %}
                      <i class="fas fa-lock lock-card-icon"></i>
                      {% endif %}{% else %}{% url 'account_login' %}{% endif %}

                        <img class="service-cards-img"
                          src="{% if service.thumbnail %}{{ service.thumbnail.url }}{% else %} {% static 'img/images/post_img6.png' %} {% endif %}">
                        <div class="our-service-buttons">
                          {% for tag in service.tags.all %}
                          <button class="button-ist-servive" type="button">{{tag.name}} {{status}}</button>
                          {% endfor %}
                        </div>
                        <div class="content-right big service_card_overlay">
                          <h6>
                            {% for tag in service.tags.all %}
                            <span class="cate_badge ms-0 me-2 d-inline-block mb-2">{{tag.name}}</span>
                            {% endfor %}
                            <span class="blog_publish">{{service.created_at}}</span>
                          </h6>
                          <h3 class="text_dotted post_right_content color-w">{{service.title}}</h3>
                        </div>
                      </div>
                    </a>
                  </div>
                  {% endfor %}
                  {% else %}
                  <h1>no data</h1>>
                  {% endif %}
                  <button class="primary_btn subscribe_btn desk-hide border-0">View More</button>
                  <div id="bottom-sentinel">
                    <div class="loader" style="display:none;"></div>
                  </div>
                </div>
              </div>
            </div>
            <!-- end our service tabs -->
            
            <!-- service cards section -->
            <!-- end service cards section -->
          </div>
        </section>
      <!-- end our service section -->
    </div>


    
    <!-- ======= Footer ======= -->
    {% include 'includes/footer.html' %}
    <!-- End Footer -->
    
  </div>
</div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/infinite.js' %}"></script>
<script>
  document.addEventListener("DOMContentLoaded", () => {
    let bottomSentinel = document.querySelector("#bottom-sentinel");
    let scrollElement = document.querySelector("#service-content-grid-section");
    let baseUrl = "{% url 'finsight' %}";

    attachInfiniteScroll(bottomSentinel, scrollElement, baseUrl);
  })
</script>


<script>
    loadAvailableFinsight = (url, searchID, divID) => {
      jQuery.ajax({
        url: url,
        data: {
          'search_id': searchID
        },
        success: function (data) {
          jQuery("#" + divID).html(data);

        }
      });
    }

  jQuery("#search-input").on('keyup', function () {
    searchID = jQuery('#search-input').val()
    url = "{% url 'finsight-grid-search' %}"
    loadAvailableFinsight(url, searchID, 'service-content-grid-section')
  });
  jQuery("#search-button").on('click', function () {
    searchID  = jQuery('#search-button').val()
    url = "{% url 'finsight-grid-search' %}"
    loadAvailableFinsight(url, searchID, 'service-content-grid-section')
  });

  jQuery("#search-input").on('keyup', function () {
    searchID = jQuery('#search-input').val()
    console.log("search id is ", searchID)
    url = "{% url 'finsight-list-search' %}"
    loadAvailableFinsight(url, searchID, 'service-content-table-section')
  });
  jQuery("#search-button").on('click', function () {
    searchID = jQuery('#search-button').val()
    url = "{% url 'finsight-list-search' %}"
    loadAvailableFinsight(url, searchID, 'service-content-table-section')
  });
</script>

{% endblock %}

app/templates/subscription/real_time_search_grid.html
{% load static %}
{% if filter_alerts %}
{% for alert in filter_alerts %}
<div class="col-md-6 col-lg-6 col-sm-12" >
  <a href="{% url 'view_alert' alert.slug %}">
  <div class="service-cards post-right mt-5">
    <img class="service-cards-img" src="{% if alert.thumbnail %}{{ alert.thumbnail.url }}{% else %} {% static 'img/images/post_img1.png' %} {% endif %}">
    <div class="our-service-buttons">
      {% for tag in alert.tags.all %}
      <button class="button-ist-servive" type="button">{{tag.name}}</button>
      {% endfor %}
    </div>
    <div class="content-right big service_card_overlay">
      <h6>
        {% for tag in alert.tags.all %}
        <span class="cate_badge ms-0 me-2 d-inline-block mb-2">{{tag.name}}</span> 
        {% endfor %}
        <span class="blog_publish">{{alert.created_at}}</span>
      </h6>
      <h3 class="text_dotted post_right_content color-w">{{alert.message}}</h3>
    </div>
  </div>
  </a>
</div>
{% endfor %}
{% endif %}

app/templates/subscription/real_time_search_list.html
{% load static %}
{% if filter_alerts %}
{% for alert in filter_alerts %}
<tr>
  <td>
    <a href="{% url 'view_alert' alert.slug %}">{{alert.asset_name}}</a>
  </td>
    <td>{% for tag in alert.tags.all %}{{tag.name}} {% endfor %}</td>
    <td>{{alert.asset_class}}</td>
  </tr>
{% endfor %}
{% else %}
<h1>no data found</h1>
{% endif %} 

app/templates/subscription/search_insign_grid.html
{% load static %}
{% if filter_finsights %}
{% for service in filter_finsights %}
<div class="col-md-6 col-lg-6 col-sm-12" >
  <a href="{% if user.is_authenticated %}{% if service.plans.price|slugify == Free_Plan_PRICE %}{{service.link}}{% elif service.plans in user_current_plan %}{{service.link}}{% else %}#{% endif %}{% else %}{% url 'account_login' %}{% endif %}">
  <div class="service-cards post-right mt-5">

    {% if user.is_authenticated %}{% if service.plans.price|slugify == Free_Plan_PRICE %}{% elif service.plans in user_current_plan %}{% else %}
    <i class="fas fa-lock lock-card-icon"></i>
    {% endif %}{% else %}{% url 'account_login' %}{% endif %}

    <img class="service-cards-img" src="{% if service.thumbnail %}{{ service.thumbnail.url }}{% else %} {% static 'img/images/post_img6.png' %} {% endif %}">
    <div class="our-service-buttons">
      {% for tag in service.tags.all %}
      <button class="button-ist-servive" type="button">{{tag.name}}</button>
      {% endfor %}
    </div>
    <div class="content-right big service_card_overlay">
      <h6>
        {% for tag in service.tags.all %}
        <span class="cate_badge ms-0 me-2 d-inline-block mb-2">{{tag.name}}</span> 
        {% endfor %}
        <span class="blog_publish">{{service.created_at}}</span>
      </h6>
      <h3 class="text_dotted post_right_content color-w">{{service.title}}</h3>
    </div>
  </div>
</a>
</div>
{% endfor %}
{% endif %}

app/templates/subscription/search_insign_list.html
{% load static %}
{% if filter_finsights %}
{% for service in filter_finsights %}
<tr>
  <td>
    <a href="{% if user.is_authenticated %}{% if service.plans.price|slugify == Free_Plan_PRICE %}{{service.link}}{% elif service.plans in user_current_plan %}{{service.link}}{% else %}#{% endif %}{% else %}{% url 'account_login' %}{% endif %}">
    {{service.title}}</a>
  </td>
    <td>{% for tag in service.tags.all %}{{tag.name}} {% endfor %}</td>
  <!-- <td>Category</td> -->
</tr>
{% endfor %}

{% else %}
<h1>no data found</h1>
{% endif %} 

app/templates/subscription/success.html
{% extends "base.html" %}
{% load static %}

{% block style %}

<style>
  .ps-6{
     padding-left: 8rem !important; 
  }
</style>

{% endblock %}


{% block content %}

<div class="main-wrap">
  {% include 'includes/sidebar.html' %}
    
    <div class="right-bar">
      <!-- ======= Header ======= -->
      {% include 'includes/header.html' %}
      <!-- End Header -->
    
      <div>
      </div>
    
      <!-- ======= Footer ======= -->
      {% include 'includes/footer.html' %}
      <!-- End Footer -->
    
      </div>
    </div>
    </div>

{% endblock %}